### ISSUE TITLE
Artifacts in brown noise

### ISSUE THREAD

**Issue by whym** [cliambrown/EasyNoise#4]
I think I hear very small artifacts in the 'brown' sound: 4 faint notes with raising pitches, roughly 1 second apart. (It might be easier to recognize if you repeat it for several minutes.) Was there anything that might introduce such artifacts in the conversion process from ogg to wav?

I recreated a wav file from the specified source (https://en.wikipedia.org/wiki/File:Brownnoise.ogg), and the artifacts didn't reproduce in that version.

Here is the procedure I used:
`wget https://upload.wikimedia.org/wikipedia/commons/c/c9/Brownnoise.ogg &&  ffmpeg -t 5s -i Brownnoise.ogg -ac 1 brown_noise.wav`

[brown_noise.zip](https://github.com/cliambrown/EasyNoise/files/8331373/brown_noise.zip)

**Comment by cliambrown** [comment]
Thanks! I don't use the brown noise option myself, so I hadn't noticed the artifacts. I've replaced my file with your version — hope that helps.

**Comment by cliambrown** [comment]
Fixed in v0.7: https://github.com/cliambrown/EasyNoise/releases/tag/v0.7
